# Generated by Django 3.2 on 2021-07-12 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='championdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=50)),
                ('Dtoken', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('dimg', models.ImageField(blank=True, null=True, upload_to='departmentimgs/')),
            ],
        ),
        migrations.CreateModel(
            name='userlogindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stafflogindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuename', models.CharField(max_length=100)),
                ('issuedesc', models.CharField(max_length=255)),
                ('issueimg', models.ImageField(blank=True, height_field='issueimg_height', null=True, upload_to='issuesimgs/', width_field='issueimg_width')),
                ('issueimg_height', models.IntegerField(blank=True, default=200, null=True)),
                ('issueimg_width', models.IntegerField(blank=True, default=200, null=True)),
                ('issue_token', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('issuedepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.department')),
            ],
        ),
        migrations.CreateModel(
            name='HODlogindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.hodlogindata'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('opendate', models.DateField(auto_now_add=True)),
                ('accountdate', models.DateField(blank=True, null=True)),
                ('issue', models.CharField(max_length=500)),
                ('corrective', models.CharField(blank=True, max_length=400)),
                ('status', models.BooleanField(default=False)),
                ('verification', models.BooleanField(default=False)),
                ('crictcality', models.BooleanField(default=False)),
                ('forward', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, default='userissuesimgs/noimage.png', null=True, upload_to='userissuesimgs/')),
                ('resolved_img', models.ImageField(blank=True, null=True, upload_to='resolvedimgs/')),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('cid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.championdata')),
                ('complaint_issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.issues')),
                ('did', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.department')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.stafflogindata')),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.userlogindata')),
            ],
        ),
        migrations.AddField(
            model_name='championdata',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.department'),
        ),
        migrations.AddField(
            model_name='championdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='attempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('champid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.championdata')),
                ('complid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.complaint')),
            ],
        ),
    ]
