# Generated by Django 3.2.5 on 2021-07-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_stafflogindata_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflogindata',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.department'),
        ),
    ]
