# Generated by Django 3.2 on 2021-06-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_desc', models.CharField(max_length=200)),
                ('currentdate', models.DateField(blank=True, null=True)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('nextdate', models.DateField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('freq', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_desc', models.CharField(max_length=200, null=True)),
                ('standard_type', models.CharField(choices=[('B', 'Binary'), ('R', 'Range'), ('V', 'Value')], max_length=1)),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='standard_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='standard_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.BooleanField(blank=True, default=False, null=True)),
                ('upper_limit', models.BooleanField(blank=True, default=False, null=True)),
                ('less_than', models.IntegerField(blank=True, null=True)),
                ('more_than', models.IntegerField(blank=True, null=True)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='standard_binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_desc', models.CharField(max_length=200)),
                ('assembly_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.assembly')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine')),
            ],
        ),
        migrations.CreateModel(
            name='frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(blank=True, null=True)),
                ('Fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('checkpoint_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.checkpoint')),
            ],
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='part_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.part'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine'),
        ),
    ]
