# Generated by Django 3.2.5 on 2021-07-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_desc', models.CharField(max_length=200)),
                ('fromdate', models.DateField(blank=True, null=True)),
                ('nextdate', models.DateField(blank=True, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('freq', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateField(blank=True, null=True)),
                ('Fromdate', models.DateField()),
                ('todate', models.DateField()),
                ('checked', models.BooleanField(default=False)),
                ('checkpoint_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='range_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.BooleanField(blank=True, default=False, null=True)),
                ('upper_limit', models.BooleanField(blank=True, default=False, null=True)),
                ('less_than', models.IntegerField(blank=True, null=True)),
                ('more_than', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_desc', models.CharField(max_length=200, null=True)),
                ('standard_type', models.CharField(choices=[('B', 'Binary'), ('R', 'Range'), ('V', 'Value'), ('T', 'RYB')], max_length=1)),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.checkpoint')),
            ],
        ),
        migrations.CreateModel(
            name='tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='standard_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='stanvalue/')),
                ('status', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='standard_ryb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='rybimg/')),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='standard_range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='stanrange/')),
                ('status', models.BooleanField(default=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency')),
                ('rangevalue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.range_value')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='standard_binary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='stanbinary/')),
                ('time', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_desc', models.CharField(max_length=200)),
                ('assembly_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.assembly')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine')),
            ],
        ),
        migrations.CreateModel(
            name='mainhodlogindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.mainhodlogindata'),
        ),
        migrations.AddField(
            model_name='machine',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.reviewer'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='part_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.part'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.machine'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.tester'),
        ),
    ]
