# Generated by Django 3.2 on 2021-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='currentdate',
        ),
        migrations.AddField(
            model_name='frequency',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
