# Generated by Django 3.2 on 2021-06-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20210604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_range',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
