# Generated by Django 3.2 on 2021-06-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20210608_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_range',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
