# Generated by Django 3.2 on 2021-06-11 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_standard_range_rangevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_range',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency'),
        ),
    ]
