# Generated by Django 3.2 on 2021-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_standard_range_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
