# Generated by Django 3.2 on 2021-06-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_frequency_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='value',
        ),
        migrations.RemoveField(
            model_name='standard_range',
            name='rangevalue',
        ),
        migrations.AlterField(
            model_name='standard_range',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency'),
        ),
    ]
