# Generated by Django 3.2 on 2021-06-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20210611_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_range',
            name='rangevalue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.range_value'),
        ),
    ]
