# Generated by Django 3.2 on 2021-06-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_standard_range_rangevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='standard_type',
            field=models.CharField(choices=[('B', 'Binary'), ('R', 'Range'), ('V', 'Value'), ('T', 'RYB')], max_length=1),
        ),
        migrations.CreateModel(
            name='standard_ryb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r', models.IntegerField()),
                ('y', models.IntegerField()),
                ('b', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('frequency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.frequency')),
                ('standard_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.standard')),
            ],
        ),
    ]
