# Generated by Django 3.2 on 2021-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_standard_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard_binary',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
