# Generated by Django 3.2 on 2021-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_auto_20210624_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='time',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
