# Generated by Django 3.2 on 2021-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_auto_20210624_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_range',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
