# Generated by Django 3.2 on 2021-07-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0018_alter_standard_range_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_ryb',
            name='b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard_ryb',
            name='r',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard_ryb',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard_ryb',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standard_value',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
