# Generated by Django 3.2 on 2021-07-16 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_mainhodlogindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.mainhodlogindata'),
        ),
        migrations.AddField(
            model_name='machine',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.reviewer'),
        ),
        migrations.AddField(
            model_name='machine',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.tester'),
        ),
    ]
