# Generated by Django 3.2 on 2021-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_auto_20210716_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_binary',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard_range',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard_ryb',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standard_value',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
